var ConstActionType = {
	BUTTON_NEXT: "BUTTON_NEXT",
	SET_LOCAL_STREAM: "SET_LOCAL_STREAM",
	SET_REMOTE_STREAM: "SET_REMOTE_STREAM",
	SET_CONNECTION_STATUS: "SET_CONNECTION_STATUS",
	PEER_CALL_CREATED: "PEER_CALL_CREATED",
	SOCKET_IO_CONNECTED: "SOCKET_IO_CONNECTED",
	PEER_DATA_CONNECTION_CREATED: "PEER_DATA_CONNECTION_CREATED",
	CALL_CLOSED_PASSIVELY: "CALL_CLOSED_PASSIVELY",
	CHAT_MESSAGE_RECEIVED: "CHAT_MESSAGE_RECEIVED",
	CHAT_MESSAGE_SUBMITTED: "CHAT_MESSAGE_SUBMITTED"
};

module.exports = ConstActionType;
