const Topics = {
  STATE_CHANGED: 'STATE_CHANGED',

  STREAM_LOCAL_RECEIVED: 'STREAM_LOCAL_RECEIVED',
  STREAM_REMOTE_RECEIVED: 'STREAM_LOCAL_RECEIVED',
  STREAM_LOCAL_CHANGED: 'STREAM_LOCAL_CHANGED',

  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_CHANGED: 'MESSAGE_CHANGED',

  CLOSE_EMOTICON_PICKER: 'CLOSE_EMOTICON_PICKER',

  REQUEST_NEW_PARTNER: 'REQUEST_NEW_PARTNER',
  ID_LOCAL_CHANGED: 'ID_LOCAL_CHANGED',
  ID_PARTNER_CHANGED: 'ID_PARTNER_CHANGED',

  DATA_CHANNEL_OPENED: 'DATA_CHANNEL_OPENED',
  DATA_CHANNEL_CLOSED: 'DATA_CHANNEL_CLOSED'
};

module.exports = Topics;
