const Topics = {
  STATE_CHANGED: 't01',

  STREAM_LOCAL_RECEIVED: 't02',
  STREAM_REMOTE_RECEIVED: 't03',
  STREAM_LOCAL_CHANGED: 't04',

  MESSAGE_RECEIVED: 't05',
  MESSAGE_SEND: 't06',
  MESSAGE_CHANGED: 't07',

  CLOSE_EMOTICON_PICKER: 't08',

  REQUEST_NEW_PARTNER: 't09',
  ID_LOCAL_CHANGED: 't10',
  ID_PARTNER_CHANGED: 't11',

  DATA_CHANNEL_OPENED: 't12',
  DATA_CHANNEL_CLOSED: 't13',

  TOGGLE_WEBCAM_PREFERENCE: 't14'
};

module.exports = Topics;
